---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./coffee-shop-app-of-apps.yaml
- ./coffee-shop-projects.yaml
- ./coffee-shop-database.yaml
- ./coffee-shop.yaml
- ./barista.yaml
- ./coffee-shop-pipeline.yaml
